language: elixir

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.5

elixir:
  - 1.10
  - 1.9
  - 1.8
  - 1.7
otp_release:
  - 22.0
  - 21.0
  - 20.0

jobs:
  exclude:
    - elixir: 1.10
      otp_release: 20.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - docker-compose build

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

before_script:
  # - mix compile
  - MIX_ENV=test mix compile

script:
  - docker-compose up --detach
  - curl --version
  # - curl -v --proxy localhost:8888 https://jsonplaceholder.typicode.com/todos/44
  # - curl -v --proxy localhost:8888 https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente
  # - mix test test/integration/httpoison.exs --trace --seed 0
  - mix test test/integration/hackney_test.exs --trace --seed 77422
  - mix test test/integration/curl_test.exs --trace --seed 0
  - mix test test/integration/mint_test.exs --trace --seed 0
  - mix test test/integration/httpc_test.exs --trace --seed 0
  - mix test test/integration/ibrowse_test.exs --trace --seed 0
  - mix test test/integration/gun_test.exs --trace --seed 0

after_script:
  - docker-compose down

# script:
  # - mix format --check-formatted
  # - mix credo --strict
  # - mix dialyzer
  # - mix test
  # - mix coveralls.travis --trace

cache:
  directories:
    - ~/.hex
    - ~/.mix
    - _build
    - priv/plts

# Leave only .plt files in build
before_cache:
  - mix deps.clean --all --build
  - mix clean --build
